// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDI8b9jqCAUFlpN_kRXZWRpbIPRRESipkU',
//     appId: '1:873207139041:web:b96db057cbfce55f87c5a0',
//     messagingSenderId: '873207139041',
//     projectId: 'amber-app-99014',
//     authDomain: 'amber-app-99014.firebaseapp.com',
//     storageBucket: 'amber-app-99014.firebasestorage.app',
//     measurementId: 'G-VFKBJ35QPQ',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCzURX9noMKMTWDyocWe8UEyn2wG0LtJ2I',
//     appId: '1:873207139041:android:f126683290d3c83987c5a0',
//     messagingSenderId: '873207139041',
//     projectId: 'amber-app-99014',
//     storageBucket: 'amber-app-99014.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCvD_7d2GMRfit3NjljLt_-RI_qoqRwgSo',
//     appId: '1:873207139041:ios:c2900357943c294087c5a0',
//     messagingSenderId: '873207139041',
//     projectId: 'amber-app-99014',
//     storageBucket: 'amber-app-99014.firebasestorage.app',
//     iosBundleId: 'com.example.amberApp',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCvD_7d2GMRfit3NjljLt_-RI_qoqRwgSo',
//     appId: '1:873207139041:ios:c2900357943c294087c5a0',
//     messagingSenderId: '873207139041',
//     projectId: 'amber-app-99014',
//     storageBucket: 'amber-app-99014.firebasestorage.app',
//     iosBundleId: 'com.example.amberApp',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDI8b9jqCAUFlpN_kRXZWRpbIPRRESipkU',
//     appId: '1:873207139041:web:17588def50780a8a87c5a0',
//     messagingSenderId: '873207139041',
//     projectId: 'amber-app-99014',
//     authDomain: 'amber-app-99014.firebaseapp.com',
//     storageBucket: 'amber-app-99014.firebasestorage.app',
//     measurementId: 'G-380NPCDC9S',
//   );
//
// }